covid_env/FightCovid19/urls.py
from django.contrib import admin
from django.urls import path
from covidApp.views import HomePageView, NewsPostView, StatisticsView, ToolsPostView, AwarenessPostView, contact_form
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView, name="HomePage"),
    path('News/', NewsPostView.as_view(), name="News"),
    path('Statistics/', StatisticsView, name="Statistics"),
    path('Tools/', ToolsPostView.as_view(), name="Tools"),
    path('Awareness/', AwarenessPostView.as_view(), name="Awareness"),
    path('Contact/', contact_form, name="ContactView"),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

covid_env/covidApp/models.py
from django.db import models

# News::Title - body - date - resource -img


class NewsPost(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField(default=' ')
    img = models.ImageField(
        upload_to='news/', null=True, blank=True)
    resource = models.CharField(max_length=64, default='', blank=True)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class ToolsPost(models.Model):
    tools = [('Masks', 'اقنعة'), ('Sterilizers', 'معقمات'),
             ('Gloves', 'كفوف'), ('Recomended', 'الموصى بها')]

    category = models.CharField(max_length=128, choices=tools)
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField(default=' ', blank=True)
    img = models.ImageField(
        upload_to='tools/', null=True, blank=True)

    def __str__(self):
        return self.title


class AwarenessPost(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField(default=' ')
    img = models.ImageField(
        upload_to='awareness/', null=True, blank=True)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class BePositivePost(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField(default=' ')
    img = models.ImageField(
        upload_to='bePositive/', null=True, blank=True)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

covid_env/covidApp/forms.py
from django import forms

from django import forms
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User


def should_be_empty(value):
    if value:
        raise forms.ValidationError('Field is not empty')


class ContactForm(forms.Form):
    name = forms.CharField(label='الاسم', max_length=80)
    message = forms.CharField(label='الرسالة', widget=forms.Textarea)
    email = forms.EmailField(label='البريد الالكتروني')
    forcefield = forms.CharField(
        required=False, widget=forms.HiddenInput, label="Leave empty", validators=[should_be_empty])


# # Override the UserCreationForm
# class UserCreateForm(UserCreationForm):
#     email = forms.EmailField(required=True, label='Email', error_messages={
#                              'exists': 'This already exists!'})

#     class Meta:
#         model = User
#         fields = ('username', 'email', 'password1', 'password2')

#     def save(self, commit=True):
#         user = super(UserCreateForm, self).save(commit=False)
#         user.email = self.cleaned_data['email']
#         if commit:
#             user.save()
#         return user

#     def clean_email(self):
#         if User.objects.filter(email=self.cleaned_data['email']).exists():
#             raise forms.ValidationError(
#                 self.fields['email'].error_messages['exists'])
#         return self.cleaned_data['email']

# class ContactForm(forms.Form):
#     name = forms.CharField(label='الاسم',max_length=128, required=True)
#     email = forms.EmailField(required=False)
#     title = forms.CharField(max_length=128, required=True)
#     # content = forms.TextField()
#     # img = forms.ImageField(
#     #     upload_to='contact/', null=True, blank=True)
#     # date = forms.DateTimeField(auto_now_add=True)

#     # def __str__(self):
#     #     return self.title

covid_env/covidApp/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView, DetailView
from .models import NewsPost, ToolsPost, AwarenessPost

from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
# from django.contrib.auth import authenticate, login


def HomePageView(request):
    return render(request, "HomePage.html")


def StatisticsView(request):
    return render(request, "Statistics.html")


def ContactView(request):
    return render(request, "Contact.html")


class NewsPostView(View):
    def get(self, request):
        News_Posts = NewsPost.objects.all().order_by('-date')
        pt = 'الاخبار'
        context = {'NewsPosts': News_Posts, 'PT': pt}
        return render(request, 'News.html', context)


class ToolsPostView(View):
    def get(self, request):
        Tools_Posts = ToolsPost.objects.all().order_by('category')
        pt = 'ادوات الوقاية'
        context = {'ToolsPosts': Tools_Posts, 'PT': pt}
        return render(request, 'Tools.html', context)


class AwarenessPostView(View):
    def get(self, request):
        Awareness_Posts = AwarenessPost.objects.all().order_by('-date')
        pt = 'طريق الوقاية'
        context = {'AwarenessPost': Awareness_Posts, 'PT': pt}
        return render(request, 'Awareness.html', context)


def contact_form(request):
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = f'Message from {form.cleaned_data["name"]}'
            message = form.cleaned_data["message"]
            sender = form.cleaned_data["email"]
            recipients = ['mustafa.raad.m7@gmail.com']
            try:
                send_mail(subject, message, sender,
                          recipients, fail_silently=True)
            except BadHeaderError:
                return HttpResponse('Invalid header found')
            return HttpResponse('Success...Your email has been sent')
    return render(request, 'Contact.html', {'form': form})

covid_env/covidApp/templates/Awareness.html
{% extends 'Navs.html' %}
{% block title %}الوقاية{% endblock title %}
{% load static %}
{% block content %}
            <p class="navbar-brand mx-auto my-auto"><strong class="h4">{{PT}}</strong></p>
{% endblock content %}

{% block body %}
<link rel="stylesheet" href="{% static './style/News.css' %}">
{% comment %} <main id="mainPost"> {% endcomment %}
    {% for aware in AwarenessPost %}
    <section class="container">
        <header>
            <h2>{{aware.title}}</h2>
        </header>
        <article>
            <p class="text-right">
                {{aware.content}}
            </p>
        </article>
        {% if aware.img %}
        <div class="row image">
            <img src="{{aware.img.url}}" class="card-img-top" alt="...">
        </div>
        {% endif %}
        
        <div class="row">
            <sub>{{aware.date}}</sub>
        </div>
    </section>
    {% endfor %}
    {% comment %} </main> {% endcomment %}
{% endblock body %}

covid_env/covidApp/templates/Contact.html
{% extends 'Navs.html' %}
{% block title %}التواصل{% endblock title %}
{% load static %}
{% block content %}
<p class="navbar-brand mx-auto my-auto"><strong class="h4">التواصل</strong></p>
{% endblock content %}
{% block body %}
<link rel="stylesheet" href="{% static './style/News.css' %}">
    <section class="text-right">
        <!-- <style>
            .container {
                padding-top: 15px;
            }
        
            #id_name {
                width: 100%
            }
        
            #id_message {
                width: 100%
            }
        
            #id_email {
                width: 100%
            }
        </style>
        
        <div class="container ">
            <h2>Send Me a Message</h2>
            <form action="" method="POST">
                {% csrf_token %}
        
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
        
                {% for field in form.visible_fields %}
                <div class="form-group">
                    {{ field.errors }}
                    <label>{{ field.label_tag }}</label>
                    <p>{{ field }}</p>
                </div>
                {% endfor %}
                <button type="reset" class="btn btn-secondary">Reset</button>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div> -->

        <form class="container" action="" method="POST" dir="rtl">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}

            {{ field.errors }}
            <div class="form-group">
                <label >{{ field.label_tag }}</label>
                <div class="">
                    {{ field }}
                </div>
                <!-- <input type="text" class="form-control text-right" id="exampleFormControlInput1"
                    placeholder="اسم المستخدم"> -->
            </div>
            <!-- <div class="form-group">
                <label for="exampleFormControlInput3">البريد الالكتروني</label>
                <input type="email" class="form-control text-right" id="exampleFormControlInput3"
                    placeholder="name@example.com">
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput2">العنوان</label>
                <input type="text" class="form-control text-right" id="exampleFormControlInput2"
                    placeholder="عنوان الرسالة">
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput4">الرسالة</label>
                <textarea rows="5" class="form-control text-right" id="exampleFormControlInput4"
                    placeholder="الرسالة"></textarea>
            </div> -->
            {% endfor %}
            <div class="text-center">
                <button type="submit" id="" class="btn btn-primary w-25">حذف</button>
                <button type="submit" id="" class="btn btn-primary w-25">اضافة صورة</button>
                <button type="submit" id="" class="btn btn-primary w-25">ارسال</button>
            </div>
        </form>


    </section>

{% endblock body %}

covid_env/covidApp/templates/HomePage.html
{% extends 'Navs.html' %}
{% block title %}الرئيسية{% endblock title %}
{% load static %}
{% block content %}
<p class="navbar-brand mx-auto my-auto"><strong class="h4">لنحارب كورونا</strong></p>
{% endblock content %}

{% block body %}
<link rel="stylesheet" href="{% static './style/HomePage.css' %}">
<!-- ---------------------------------------------------------------Main--------------------------------------------------------------- -->
<div class="container text-center ">
    <!-- ---------------------------------------------------------------row 1--------------------------------------------------------------- -->

    <div class="row">
        <div class="col-6" style="z-index: 1;">
            <span class="dot ">
                <h4>
                    <b>حمى</b>
                </h4>
        </div>
        <div class="col-6" style="z-index: 1;">
            <span class="dot">
                <h4>
                    <b>فلاونزا</b>
                </h4>
            </span>
        </div>
    </div>
    <!-- ---------------------------------------------------------------row 2--------------------------------------------------------------- -->
    <div class="row">
        <div class="col-3 offset-3">
            <div id="lineUL"> </div>
        </div>
        <div class="col-3">
            <div id="lineUR"></div>
        </div>
    </div>
    <!-- ---------------------------------------------------------------row 3--------------------------------------------------------------- -->
    <div class="row">
        <div class="col-12" style="z-index: 2;">
            <span class="dot-centered animecenter">
                <span class="">
                    <h2> فيروس كورونا <br>
                        COVID-19
                    </h2>
                </span>
        </div>
    </div>
    <!-- ---------------------------------------------------------------row 2--------------------------------------------------------------- -->
    <div class="row">
        <div class="col-3 offset-3">
            <div id="lineDL"> </div>
        </div>
        <div class="col-3">
            <div id="lineDR"></div>
        </div>
    </div>
    <!-- ---------------------------------------------------------------row 5--------------------------------------------------------------- -->
    <div class="row">
        <div class="col-6">
            <span class="dot ">
                <h4>
                    <b>عطاس</b>
                </h4>
            </span>
        </div>
        <div class="col-6 circle-1">
            <span class="dot">
                <h4>
                    <b>ضيق تنفس</b>
                </h4>
            </span>
        </div>
    </div>
</div>
<!-- ---------------------------------------------------------------End Container--------------------------------------------------------------- -->
{% comment %} {% endfor %} {% endcomment %}
</main>
{% endblock body %}

covid_env/covidApp/templates/Navs.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static './style/Navs.css' %}">
    <!-- <link rel="stylesheet" href="{% static './style/HomePage.css' %}"> -->
    <title>{% block title %} {{page_title}} {% endblock title %}</title>
</head>

<body>
    <!-- ---------------------------------------------------------------Nav--------------------------------------------------------------- -->
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="navbar-collapse collapse w-100 order-0 ">
            <ul class="navbar-nav mr-auto">
                <a class="nav-link navbar-brand my-auto" href="/">Fight COVID-19 project</a>
            </ul>
        </div>
        <div class="mx-auto order-1">
            {% block content %}
            {% endblock %}
        </div>
        <div class="navbar-collapse  w-100 order-2">
            <ul class="navbar-nav ml-auto" id="up">
                <div id="bar"></div>
            </ul>
        </div>
    </nav>
    <!-- ---------------------------------------------------------------End Nav--------------------------------------------------------------- -->
    <!-- ---------------------------------------------------------------Side Nav--------------------------------------------------------------- -->

    <div id="mySidenav" class="sidenav">
        <div class="icon-side">
            <a href="/"> <i class="fas fa-home" aria-hidden="true"></i> <span>الرئيسية</span></a>
        </div>
        <div class="icon-side">
            <a href="/News"> <i class="fas fa-newspaper" aria-hidden="true"></i> <span>الاخبار</span></a>
        </div>
        <div class="icon-side">
            <a href="/Statistics"> <i class="fas fa-poll"></i> <span>احصائيات</span></a>
        </div>
        <div class="icon-side">
            <a href="/Tools"> <i class="fas fa-head-side-mask"></i> <span>ادوات الوقاية</span></a>
        </div>
        <div class="icon-side">
            <a href="/Awareness"> <i class="fas fa-shield-virus"></i><span>طرق الوقاية</span></a>
        </div>
        <div class="icon-side">
            <a href="/BePositive"><i class="fas fa-virus-slash"></i><span>كن ايجابيا</span></a>
        </div>
        <div class="icon-side">
            <a href="/Contact"><i class="fas fa-envelope"></i><span>تواصل معنا</span></a>
        </div>
    </div>
    <!-- ---------------------------------------------------------------End Side Nav--------------------------------------------------------------- -->
    <!-- ---------------------------------------------------------------Main--------------------------------------------------------------- -->
    <main id="main">
        {% block body %}

        {%endblock%}
    </main>
    <!-- ---------------------------------------------------------------Script--------------------------------------------------------------- -->
    <footer>
        Copyrights &copy; Musatafa Raad Mutashar
    </footer>
    <script>
        var closebtn = '<a href="javascript:void(0)" role="button" class="btn nav-item closebtn" onclick="closeNav()" ><i class="fas fa-times" aria-hidden="true"></i></a>';
        var openbtn = '<a class="btn nav-item" role="button" onclick="openNav()"><i class="navbar-toggler-icon" aria-hidden="true"></i></a>';


        let opener = document.createElement('div');
        opener.id = 'opener';
        opener.innerHTML = openbtn;
        up.appendChild(opener);



        var opened = false;

        function openNav() {
            document.getElementById("opener").remove();
            let closer = document.createElement('div');
            closer.id = 'closer';
            closer.innerHTML = closebtn;
            up.appendChild(closer);
            document.getElementById("mySidenav").style.right = "0px";
            document.getElementById("main").style.marginRight = "100px";
            document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
        }

        function closeNav() {
            document.getElementById("closer").remove();
            let opener = document.createElement('div');
            opener.id = 'opener';
            opener.innerHTML = openbtn;
            up.appendChild(opener);
            document.getElementById("mySidenav").style.right = "-180px";
            document.getElementById("main").style.marginRight = "0";
            document.body.style.backgroundColor = "white";
        }
    </script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://kit.fontawesome.com/be7ca0ba3d.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

covid_env/covidApp/templates/News.html
{% extends 'Navs.html' %}
{% block title %}الاخبار{% endblock title %}
{% load static %}
{% block content %}
<p class="navbar-brand mx-auto my-auto"><strong class="h4">{{PT}}</strong></p>
{% endblock content %}
{% block body %}
<link rel="stylesheet" href="{% static './style/News.css' %}">
{% comment %} <main id="mainPost"> {% endcomment %}
    {% for post in  NewsPosts %}
    <section class="container">
        <header>
            <h2>{{post.title}}</h2>
        </header>
        <article>
            <p class="text-right">
                {{post.content}}
            </p>
        </article>
        <div class="row image">
                <img src="{{post.img.url}}" class="card-img-top" alt="...">
        </div>
        <div class="row">
            <sub>{{post.date}} - rsc:{{post.resource}} </sub>
        </div>
    </section>

    {% endfor %}
    {% comment %} </main> {% endcomment %}
{% endblock body %}

covid_env/covidApp/templates/Statistics.html
{% extends 'Navs.html' %}
{%load static%}
{% block title %}الاحصائيات{% endblock title %}
{% block content %}
<p class="navbar-brand mx-auto my-auto"><strong class="h4">الاحصائيات</strong></p>
{% endblock content %}

{%block body %}
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-155058741-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag() { dataLayer.push(arguments); }
  gtag('js', new Date());
  gtag('config', 'UA-155058741-2');
</script>
<script src="https://kit.fontawesome.com/4add81f750.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
  integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css"
  crossorigin="anonymous">
<link rel="stylesheet" href="{% static './style/Statistics.css' %}">


<div class="container-fluid ">
  <div class="row mb-1">
    <div class="col-sm">
      <div id="root"></div>
    </div>
  </div>
  <div class="row mb-4 ">
    <div class="col-sm">
      <small class="text-secondary text-nowrap mr-3">
        <i class="fas fa-table"></i> Data source: <a href="https://github.com/CSSEGISandData/COVID-19"
          class="text-dark">COVID-19 Data Repository by JHU CSSE</a>
      </small>
    </div>
  </div>
</div>

<!-- Load dependencies. -->
<script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script>
<!--    <script src="https://unpkg.com/react@16/umd/react.production.min.js" crossorigin></script>-->
<!--    <script src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js" crossorigin></script>-->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
  integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://unpkg.com/papaparse@5.1.1/papaparse.min.js" crossorigin></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" crossorigin></script>

<!-- Load custom scripts. -->
<script src="{% static './script/utils.js' %}"></script>
<script src="{% static './script/data.js' %}"></script>
<script src="{% static './script/Statistics.js' %}"></script>
{% endblock body %}

covid_env/covidApp/templates/Tools.html
{% extends 'Navs.html' %}
{% block title %}الادوات{% endblock title %}
{% load static %}
{% block content %}
<p class="navbar-brand mx-auto my-auto"><strong class="h4">{{PT}}</strong></p>
{% endblock content %}

{% block body %}
<link rel="stylesheet" href="{% static './style/Tools.css' %}">

<!-- <h4>position: {{ToolsPosts.get_category_display}}</h4> -->
<div class="row sel">
    <form action="{% url 'HomePage' %}" method="get"></form>
    <label for="cate" class="col-1">الاصناف</label>
    <div class="form-group col-7">
        <select class="custom-select" name="cate" id="cate">
            <option value="1">الكل</option>
            <option value="2">اقنعة</option>
            <option value="3">معقمات</option>
            <option value="4">كفوف</option>
            <option value="5">الموصى بها</option>
        </select>
    </div>
    <input type="submit" class="btn btn-primary col-2" value="صنف" />
</div>
{% for tool in ToolsPosts %}
<section class="container">
    <header>
        <h2>{{tool.title}}</h2>
            <sub>{{tool.category}} </sub>

    </header>
    <article>
        <p class="text-right">
            {{tool.content}}
        </p>
    </article>
    <div class="row image">
        <img src="{{tool.img.url}}" class="card-img-top" alt="...">
    </div>
</section>

{% endfor %}
{% endblock body %}